FROM ubuntu:14.04

ARG http_proxy=$http_proxy
ARG https_proxy=$http_proxy

ENV DEBIAN_FRONTEND noninteractive

############### xvnc / xfce installation
RUN apt-get update && apt-get upgrade -y && apt-get install -y supervisor nano xfce4 gnome-icon-theme-full

RUN apt-get install software-properties-common -y
RUN apt-get install -y python-software-properties debconf-utils

ADD jdk-8u131-linux-x64.tar.gz /usr/lib/jvm
RUN update-alternatives --install "/usr/bin/java" "java" "/usr/lib/jvm/jdk1.8.0_131/bin/java" 1
RUN update-alternatives --install "/usr/bin/javac" "javac" "/usr/lib/jvm/jdk1.8.0_131/bin/javac" 1
RUN update-alternatives --install "/usr/bin/javaws" "javaws" "/usr/lib/jvm/jdk1.8.0_131/bin/javaws" 1
RUN update-alternatives --config java
RUN update-alternatives --config javac
RUN update-alternatives --config javaws

# Open MDS
RUN apt-get update   
RUN apt-get install -y subversion
RUN apt-get install -y patch
RUN apt-get install -y patchutils
RUN apt-get install -y libc6-dev
RUN apt-get install -y libxml-dom-perl
RUN apt-get install -y zlib1g
RUN apt-get install -y zlib1g-dev
RUN apt-get install -y libcurl4-openssl-dev
RUN apt-get install -y lib32z1 lib32ncurses5 lib32bz2-1.0 lib32stdc++6

# make /bin/sh symlink to bash instead of dash:
RUN echo "dash dash/sh boolean false" | debconf-set-selections
RUN DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash

ADD ./12.0.1.tar.gz /root

WORKDIR /root/12.0.1/Linux/x86_64
RUN ./install.sh

# Open SPX Project
RUN apt-get install -y zip 
RUN apt-get install -y unzip
RUN apt-get install -y libedit2 
RUN apt-get install -y lsof 
RUN apt-get install -y php5-cli 
RUN apt-get install -y php5-common 
RUN apt-get install -y php5-json 
RUN apt-get install -y php5-readline 

# Build project
RUN apt-get install -y build-essential 
RUN apt-get install -y bc
RUN apt-get install -y libpcre3
RUN apt-get install -y libpcre3-dev

ENV JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8"

RUN apt-get install -y autoconf
RUN apt-get install automake
RUN apt-get install -y luajit
RUN apt-get install -y nodejs npm
RUN npm set strict-ssl=false
RUN npm i -gq grunt-cli bower coveralls beautifier

RUN apt-get install -y libtool
RUN apt-get install -y python-numpy
RUN apt-get install -y mtd-utils

# import purlic/private signed image key to MDS
COPY keys/public.pem /root/12.0.1/Linux/x86_64/MDS/spx/utils/BuildPRJ
COPY keys/private.pem /root/12.0.1/Linux/x86_64/MDS/spx/utils/BuildPRJ

WORKDIR /root
CMD ["12.0.1/Linux/x86_64/MDS/MDS"]

